#!/bin/bash -e

if [ ! -x nats ]; then
    GOBIN=$(pwd) go install github.com/nats-io/natscli/nats@latest
fi

mkdir -p \
  gerrit-data/.ssh \
  gerrit-data/bin \
  gerrit-data/cache \
  gerrit-data/data \
  gerrit-data/db \
  gerrit-data/etc \
  gerrit-data/git \
  gerrit-data/hooks \
  gerrit-data/index \
  gerrit-data/lib \
  gerrit-data/logs \
  gerrit-data/plugins \
  gerrit-data/static \
  jenkins-home \
  nats-data

docker stack deploy --detach=true --with-registry-auth -c swarm.yaml gerrit
