version: '3.7'

# Suggested deployment command:
#   docker --host mega4.build.couchbase.com stack deploy --with-registry-auth -c swarm.yaml gerrit
# All services, networks, etc. will then get an "gerrit_" prefix,

services:
  gerrit:
    deploy:
      replicas: 1
      # Uncomment the following to perform initial deployment
      #restart_policy:
      #  condition: none

      labels:
        - "traefik.enable=true"
        - "traefik.swarm.network=gerrit_traefik"

        - "traefik.http.routers.gerrit_http.entrypoints=web"
        - "traefik.http.routers.gerrit_http.rule=Host(`review.local`)"
        - "traefik.http.routers.gerrit_http.service=gerrit"

        - "traefik.http.services.gerrit.loadbalancer.server.port=8080"
        - "traefik.http.services.gerrit.loadbalancer.server.scheme=http"

    image: gerritcodereview/gerrit:3.10.2
    volumes:
      - ./gerrit-data/.ssh:/var/gerrit/.ssh
      - ./gerrit-data/cache:/var/gerrit/cache
      - ./gerrit-data/data:/var/gerrit/data
      - ./gerrit-data/db:/var/gerrit/db
      - ./gerrit-data/etc:/var/gerrit/etc
      - ./gerrit-data/git:/var/gerrit/git
      - ./gerrit-data/hooks:/var/gerrit/hooks
      - ./gerrit-data/index:/var/gerrit/index
      - ./gerrit-data/lib:/var/gerrit/lib
      - ./gerrit-data/logs:/var/gerrit/logs
      - ./gerrit-data/plugins:/var/gerrit/plugins
      - ./gerrit-data/static:/var/gerrit/static
      - ./nats-context:/var/gerrit/.config/nats
      - ./nats:/usr/local/bin/nats
    ports:
      - "29418:29418"
    networks:
      - nats
      - traefik
    environment:
      - CANONICAL_WEB_URL=http://review.local
    # Uncomment the following line to perform initial deployment
    #command: init

  jenkins:
    deploy:
      replicas: 1
    image: jenkins/jenkins:2.462.2
    ports:
      - "8081:8080"
    networks:
      - nats
    volumes:
      - ./jenkins-home:/var/jenkins_home
      - ./nats-context:/var/jenkins_home/.config/nats
      - ./nats:/usr/local/bin/nats

  speer:
    image: couchbasebuild/speer:latest
    volumes:
      - ../speer:/app
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.swarm.network=gerrit_traefik"

        - "traefik.http.routers.speer_http.entrypoints=web"
        - "traefik.http.routers.speer_http.rule=Host(`review.local`)"
        - "traefik.http.routers.speer_http.rule=PathPrefix(`/speer`)"
        - "traefik.http.routers.speer_http.service=speer"
        - "traefik.http.routers.speer_http.priority=100"

        - "traefik.http.services.speer.loadbalancer.server.port=8000"
        - "traefik.http.services.speer.loadbalancer.server.scheme=http"

    networks:
      - traefik

  traefik:
    image: traefik:v3.2.3
    command:
      - "--log.level=DEBUG"
      - "--providers.swarm.endpoint=unix:///var/run/docker.sock"
      - "--providers.swarm.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"

      - "--api.insecure=true"
    init: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 80:80
      - 443:443
      - 6725:8080
    deploy:
      replicas: 1
    networks:
      - traefik

  nats:
    deploy:
      replicas: 1
    image: nats:2.10.3
    command: --jetstream --store_dir /var/lib/nats
    user: 1000:1000
    volumes:
      - ./nats-data:/var/lib/nats
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - nats

networks:
  nats:
  traefik:
