version: '3.7'

# Suggested deployment command:
#   docker --host mega4.build.couchbase.com stack deploy --with-registry-auth -c swarm.yaml gerrit
# All services, networks, etc. will then get an "gerrit_" prefix,

services:
  gerrit:
    deploy:
      replicas: 1
      # Uncomment the following to perform initial deployment
      #restart_policy:
      #  condition: none
    image: gerritcodereview/gerrit:3.10.2
    volumes:
      - ./gerrit-data/.ssh:/var/gerrit/.ssh
      - ./gerrit-data/cache:/var/gerrit/cache
      - ./gerrit-data/data:/var/gerrit/data
      - ./gerrit-data/db:/var/gerrit/db
      - ./gerrit-data/etc:/var/gerrit/etc
      - ./gerrit-data/git:/var/gerrit/git
      - ./gerrit-data/hooks:/var/gerrit/hooks
      - ./gerrit-data/index:/var/gerrit/index
      - ./gerrit-data/lib:/var/gerrit/lib
      - ./gerrit-data/logs:/var/gerrit/logs
      - ./gerrit-data/plugins:/var/gerrit/plugins
      - ./gerrit-data/static:/var/gerrit/static
      - ./nats-context:/var/gerrit/.config/nats
      - ./nats:/usr/local/bin/nats
    ports:
      - "29418:29418"
      - "8080:8080"
    networks:
      - nats
    environment:
      - CANONICAL_WEB_URL=http://127.0.0.1:8080/
    # Uncomment the following line to perform initial deployment
    #command: init

  jenkins:
    deploy:
      replicas: 1
    image: jenkins/jenkins:2.462.2
    ports:
      - "8081:8080"
    networks:
      - nats
    volumes:
      - ./jenkins-home:/var/jenkins_home
      - ./nats-context:/var/jenkins_home/.config/nats
      - ./nats:/usr/local/bin/nats

  nats:
    deploy:
      replicas: 1
    image: nats:2.10.3
    command: --jetstream --store_dir /var/lib/nats
    user: 1000:1000
    volumes:
      - ./nats-data:/var/lib/nats
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - nats

networks:
  nats: